version: '3.9'
services:
  db:
    image: mongo:5.0.16-focal
    container_name: db
    ports:
      - 4000:27017
    restart: always

  azure-storage:
    image: azure-storage
    build:
      context: ./azure-storage
      dockerfile: Dockerfile
    container_name: video-storage
    ports:
      - 4001:80
    environment:
      PORT: 80
      STORAGE_ACCOUNT_NAME:
      STORAGE_ACCOUNT_KEY:
    restart: "no"

  video-streaming:
    image: video-streaming
    build:
      context: ./video-streaming
      dockerfile: Dockerfile
    container_name: video-streaming
    ports:
      - 4002:80
    environment:
      PORT: 80
      DB_HOST: mongodb://db:27017
      DB_NAME: video-streaming
      VIDEO_STORAGE_HOST: video-storage
      VIDEO_STORAGE_PORT: 80
    restart: "no"