version: '3.9'
services:
  rabbit:
    image: rabbitmq:3.11.13-management
    container_name: rabbit
    ports:
      - 5672:5672
      - 15672:15672
    restart: always

  video-streaming:
    image: video-straming
    build:
      context: ./video-streaming
      dockerfile: Dockerfile.dev
    container_name: video-streaming
    volumes:
      - /tmp/video-streaming/npm-cache:/root/.npm:z
      - ./video-streaming/src:/usr/src/app/src:z
    ports:
      - 4001:80
    environment:
      PORT: 80
      RABBIT: amqp://guest:guest@rabbit:5672
      NODE_ENV: development
    depends_on:
      - rabbit
    restart: "no"