version: '3.9'
services:
  db:
    image: mongo:5.0.16-focal
    container_name: db
    ports:
      - 27017:27017
    restart: always
  
  rabbit:
    image: rabbitmq:3.11.13-management
    container_name: rabbit
    ports:
      - 5672:5672
      - 15672:15672
    restart: always

  video-streaming:
    image: video-straming
    build:
      context: ./video-streaming
      dockerfile: Dockerfile.dev
    container_name: video-streaming
    volumes:
      - /tmp/video-streaming/npm-cache:/root/.npm:z
      - ./video-streaming/src:/usr/src/app/src:z
    ports:
      - 4001:80
    environment:
      PORT: 80
      RABBIT: amqp://guest:guest@rabbit:5672
      NODE_ENV: development
    depends_on:
      - rabbit
      - db
    restart: "no"

  history:
    image: history
    build:
      context: ./history
      dockerfile: Dockerfile.dev
    container_name: history
    volumes:
      - /tmp/history/npm-cache:/root/.npm:z
      - ./history/src:/usr/src/app/src:z
    ports:
      - 4002:80
    environment:
      PORT: 80
      RABBIT: amqp://guest:guest@rabbit:5672
      DBHOST: mongodb://db:27017
      DBNAME: history
      NODE_ENV: development
    depends_on:
      - rabbit
      - db
    restart: "no"

  video-upload:
    image: video-upload
    build:
      context: ./video-upload
      dockerfile: Dockerfile.dev
    container_name: video-upload
    volumes:
      - /tmp/video-upload/npm-cache:/root/.npm:z
      - ./video-upload/src:/usr/src/app/src:z
      - ./video-upload/uploads:/usr/src/app/uploads:z
    ports:
      - 4004:80
    environment:
      PORT: 80
      RABBIT: amqp://guest:guest@rabbit:5672
      NODE_ENV: development
    depends_on:
      - rabbit
    restart: "no"

  video-storage:
    image: mock-storage
    build:
      context: ./mock-storage
      dockerfile: Dockerfile.dev
    container_name: video-storage
    volumes:
      - /tmp/mock-storage/npm-cache:/root/.npm:z
      - ./mock-storage/src:/usr/src/app/src:z
      - ./mock-storage/storage:/usr/src/app/storage:z
    ports:
      - 4005:80
    environment:
      PORT: 80
      NODE_ENV: development
    restart: "no"

  metadata:
    image: metadata
    build:
      context: ./metadata
      dockerfile: Dockerfile.dev
    container_name: metadata
    volumes:
      - /tmp/metadata/npm-cache:/root/.npm:z
      - ./metadata/src:/usr/src/app/src:z
    ports:
      - 4006:80
    environment:
      PORT: 80
      RABBIT: amqp://guest:guest@rabbit:5672
      DBHOST: mongodb://db:27017
      DBNAME: metadata
      NODE_ENV: development
    depends_on:
      - rabbit
      - db
    restart: "no"